export const BOARD_MOUNTED = 'BOARD_MOUNTED';


// UI/User triggered actions
export const ADD_TASK_CLICKED = 'ADD_TASK_CLICKED';
export const EDIT_TASK_CLICKED = 'EDIT_TASK_CLICKED';
export const SAVE_TASK_CLICKED = 'SAVE_TASK_CLICKED';
export const CANCEL_SAVE_TASK_CLICKED = 'CANCEL_SAVE_TASK_CLICKED';
export const ARCHIVE_TASK_CLICKED = 'ARCHIVE_TASK_CLICKED';
export const DRAGGED_TASK_TO_SECTION = 'DRAGGED_TASK_TO_SECTION';
export const LOGIN_SUBMITTED = 'LOGIN_SUBMITTED';

// actions triggered by Firebase service
export const FIREBASE_TASKS_RECEIVED = 'FIREBASE_TASKS_RECEIVED';
export const FIREBASE_TASK_CREATED_OK = 'FIREBASE_TASK_CREATED_OK';
export const FIREBASE_TASK_UPDATED_OK = 'FIREBASE_TASK_UPDATED_OK';
export const FIREBASE_TASK_ARCHIVED_OK = 'FIREBASE_TASK_ARCHIVED_OK';
export const FIREBASE_TASK_ARCHIVE_FAILED = 'FIREBASE_TASK_ARCHIVE_FAILED';
export const LAYOUT_RECEIVED_OK = 'LAYOUT_RECEIVED_OK';
export const AUTHENTICATION_OK = 'AUTHENTICATION_OK';
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';
