export const BOARD_MOUNTED = 'BOARD_MOUNTED';
export const LAYOUT_FETCHED_OK = 'LAYOUT_FETCHED_OK';
export const EDIT_TASK_CLICKED = 'EDIT_TASK_CLICKED';
export const FIREBASE_TASKS_RECEIVED = 'FIREBASE_TASKS_RECEIVED';
export const ADD_TASK_CLICKED = 'ADD_TASK_CLICKED';
export const CANCEL_SAVE_TASK_CLICKED = 'CANCEL_SAVE_TASK_CLICKED';
export const FIREBASE_SAVE_TASK_REQUESTED = 'FIREBASE_SAVE_TASK_RECEIVED';
