export const TASK_ARCHIVING_REQUESTED = 'TASK_ARCHIVING_REQUESTED';
export const TASK_UPDATE_REQUESTED = 'TASK_UPDATE_REQUESTED';
export const TASK_SAVE_REQUESTED = 'TASK_SAVE_REQUESTED';
export const SYNC_START_REQUESTED = 'SYNC_START_REQUESTED';
export const AUTHENTICATION_REQUESTED = 'AUTHENTICATION_REQUESTED';
